### ISSUE TITLE
"The application “Ogmo Editor” can’t be opened."

### ISSUE THREAD

**Issue by notbored** [Ogmo-Editor-3/OgmoEditor3-CE#183]
OS: MacOS Catalina

No matter what I try the latest edition can't be opened.

**Comment by notbored** [comment]
Works fine when building from source but the itch.io download doesn't work.

**Comment by mgmarlow** [comment]
Yep, same experience here on Big Sur w/ M1. Was able to build successfully from source.

**Comment by AustinEast** [comment]
Just pushed a new build to Itch that should have this fixed. Leaving this issue open for a couple more days to ensure that it actually is 👍

**Comment by notbored** [comment]
The itch.io build now opens so that's great. New issue being you can no longer close the app unless you "Force Quit" or use the activity monitor.

**Comment by AustinEast** [comment]
make sure you’re not running the app in your downloads folder - mac apps can act kinda funky when they aren’t in the Applications directory, at least a directory with write permissions (i’m assuming the issue is from the app trying and failing to save some settings on exit, you can double check in the dev tool’s error console).

**Comment by mgmarlow** [comment]
I had the same issue when trying to open it from the downloads folder, but after moving into Applications as @AustinEast suggested it works like a charm 👍. Thanks for uploading a new build!
